In [1]:
import numpy as np

# Elementwise Operation

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a + 1

array([2, 3, 4, 5])

In [8]:
b = np.ones(4)

In [9]:
b

array([1., 1., 1., 1.])

In [11]:
a + b

array([2., 3., 4., 5.])

In [14]:
a - b

array([0., 1., 2., 3.])

In [15]:
a * b

array([1., 2., 3., 4.])

In [20]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [21]:
a.shape

(3,)

In [22]:
a = np.array([1,2,3])
b = np.array([3,2,1])

In [23]:
a > b

array([False, False,  True])

In [24]:
a < b

array([ True, False, False])

In [25]:
a = np.arange(5)

In [26]:
a

array([0, 1, 2, 3, 4])

In [27]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [28]:
np.log10(a)

/Users/debnsuma/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999])

In [29]:
np.log(a)

/Users/debnsuma/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
a

array([0, 1, 2, 3, 4])

In [32]:
b

array([3, 2, 1])

In [36]:
np.concatenate((a,b))

array([0, 1, 2, 3, 4, 3, 2, 1])

# Basic Reductions


In [37]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [38]:
x = np.array([
    [1,2],
    [3,4]
])

In [39]:
x

array([[1, 2],
       [3, 4]])

In [40]:
x.sum()

10

In [41]:
x.sum(axis=1)

array([3, 7])

In [42]:
x.min()

1

In [50]:
a = np.arange(10, 20)

In [51]:
a.max()

19

In [52]:
a.min()

10

In [53]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
a.argmax()

9

In [55]:
a.argmin()

0

In [56]:
np.all(a)

True

In [58]:
np.any(a)

True

In [59]:
np.any([True, False, False])

True

In [60]:
x = np.array([1,2,3,4])
y = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [61]:
x.mean()

2.5

In [62]:
y.mean()

4.5

In [63]:
y.mean(axis=1)

array([2.5, 6.5])

In [64]:
y.mean(axis=0)

array([3., 4., 5., 6.])

In [65]:
np.median(x)

2.5

In [66]:
np.median(y)

4.5

In [69]:
np.median(y, axis=1)

array([2.5, 6.5])

In [70]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
np.median(y, axis=0)

array([3., 4., 5., 6.])

**Example:**

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.


In [73]:
!ls

01.Intro_to_Numpy.ipynb             broadcasting.png
02.Numpy_Operations.ipynb           numerical_operations_on_array.ipynb
1_Numpy_array_object.ipynb          populations.txt


In [74]:
data = np.loadtxt('populations.txt')

In [75]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [76]:
!cat populations.txt

# year	hare	lynx	carrot
1900	30e3	4e3	48300
1901	47.2e3	6.1e3	48200
1902	70.2e3	9.8e3	41500
1903	77.4e3	35.2e3	38200
1904	36.3e3	59.4e3	40600
1905	20.6e3	41.7e3	39800
1906	18.1e3	19e3	38600
1907	21.4e3	13e3	42300
1908	22e3	8.3e3	44500
1909	25.4e3	9.1e3	42100
1910	27.1e3	7.4e3	46000
1911	40.3e3	8e3	46800
1912	57e3	12.3e3	43800
1913	76.6e3	19.5e3	40900
1914	52.3e3	45.7e3	39400
1915	19.5e3	51.1e3	39000
1916	11.2e3	29.7e3	36700
1917	7.6e3	15.8e3	41800
1918	14.6e3	9.7e3	43300
1919	16.2e3	10.1e3	41300
1920	24.7e3	8.6e3	47300


In [78]:
year, hare, lynx, carrot = data.T

In [79]:
data.T

array([[ 1900.,  1901.,  1902.,  1903.,  1904.,  1905.,  1906.,  1907.,
         1908.,  1909.,  1910.,  1911.,  1912.,  1913.,  1914.,  1915.,
         1916.,  1917.,  1918.,  1919.,  1920.],
       [30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
        22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
        11200.,  7600., 14600., 16200., 24700.],
       [ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
         8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
        29700., 15800.,  9700., 10100.,  8600.],
       [48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
        44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
        36700., 41800., 43300., 41300., 47300.]])

In [80]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [81]:
population = data[:, 1:]

In [86]:
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [88]:
population.std()

17929.041851090667

In [89]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [90]:
population.std(axis=1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [93]:
#which species has the highest population each year?
population.max(axis=1)

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [94]:
population.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

# Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.


In [98]:
np.arange(0,40,10)

array([ 0, 10, 20, 30])

In [102]:
np.tile(np.arange(0,40,10), (3,1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [105]:
a = np.tile(np.arange(0,40,10), (3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [104]:
a.T

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [107]:
a = a.T

In [108]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [109]:
b = np.arange(3)

In [110]:
b

array([0, 1, 2])

In [115]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [116]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [117]:
a = np.arange(0,40,10)

In [118]:
a

array([ 0, 10, 20, 30])

In [119]:
a.shape

(4,)

In [120]:
a[3]

30

In [124]:
a = a[:, np.newaxis]

In [125]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [126]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [127]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array Shape Manipulation


In [129]:
np.array([
    range(5),
    range(5,10)
])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [130]:
a = np.array([
    range(5),
    range(5,10)
])

In [131]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [133]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [135]:
a.T.ravel()

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

The inverse operation to flattening:

In [139]:
a = np.array([[1,2,3], [4,5,6]])

In [140]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
b = a.ravel()

In [143]:
b

array([1, 2, 3, 4, 5, 6])

In [147]:
b = b.reshape(2,3)

In [148]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
b[0,0] = 1000

In [151]:
b

array([[1000,    2,    3],
       [   4,    5,    6]])

In [152]:
a

array([[1000,    2,    3],
       [   4,    5,    6]])

In [153]:
c = a.ravel()

In [154]:
a

array([[1000,    2,    3],
       [   4,    5,    6]])

In [155]:
c

array([1000,    2,    3,    4,    5,    6])

In [160]:
c = c.reshape(3, 2)

In [161]:
c

array([[1000,    2],
       [   3,    4],
       [   5,    6]])

In [162]:
a

array([[1000,    2,    3],
       [   4,    5,    6]])

In [163]:
b

array([[1000,    2,    3],
       [   4,    5,    6]])

In [164]:
c[0,1] = 200

In [165]:
c

array([[1000,  200],
       [   3,    4],
       [   5,    6]])

In [166]:
a

array([[1000,  200,    3],
       [   4,    5,    6]])

In [167]:
b

array([[1000,  200,    3],
       [   4,    5,    6]])

**Note and       Beware: reshape may also return a copy!:**

In [172]:
a = np.zeros((3,2))

In [173]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [176]:
b = a.T.reshape(3*2)

In [177]:
b

array([0., 0., 0., 0., 0., 0.])

In [178]:
b[0] = 100

In [179]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [180]:
b

array([100.,   0.,   0.,   0.,   0.,   0.])

**Adding a Dimension**

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [183]:
a = np.array([1,2,3])

In [184]:
print(a)

[1 2 3]


In [185]:
a

array([1, 2, 3])

In [190]:
a = a[:, np.newaxis]

In [191]:
a

array([[1],
       [2],
       [3]])

In [192]:
a.shape

(3, 1)

**Dimension Shuffling**

In [193]:
a = np.arange(4*3*2).reshape(4,3,2)

In [194]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [195]:
a[3,2,1]

23

**Resizing**

In [258]:
a = np.arange(4)
a
a.resize((8,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [259]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [238]:
b = np.arange(8)


In [239]:
b.resize((16,))

In [240]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0])

In [241]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0])

In [260]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [263]:
a = np.arange(4)
a.resize((32,))

In [264]:
a

array([0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [269]:
a = np.arange(4)
a
a.resize((32,))

**Sorting Data**

In [277]:
a = np.array([
    [6,2,6,12,1,20],
    [4,5,6,7,11,2]
])

In [278]:
a

array([[ 6,  2,  6, 12,  1, 20],
       [ 4,  5,  6,  7, 11,  2]])

In [279]:
b = np.sort(a, axis=0)

In [280]:
b

array([[ 4,  2,  6,  7,  1,  2],
       [ 6,  5,  6, 12, 11, 20]])

In [283]:
c = np.sort(a) # default is axis=1

In [284]:
c

array([[ 1,  2,  6,  6, 12, 20],
       [ 2,  4,  5,  6,  7, 11]])